### ISSUE TITLE
Linux64 requires a X11 server to be running with GLX. The following valid displays were found :1.0

### ISSUE THREAD

**Issue by ibrahimyousri** [Gabesarch/TIDEE#3]
When I'm trying to run "python main.py --mode rearrangement --tag TIDEE_rearrengement_2023 --OT_dist_thresh 1.0 --thresh_num_dissimilar -1 --match_relations_walk --HORIZON_DT 30 --log_every 25 --dataset 2023 --eval_split combined
DATASET IS 2023"

it opens the AI2-Thor for a moment and gives me this error 
(TIDEE) ibrahim@ibrahim:~/TIDEE$ python main.py --mode rearrangement --tag TIDEE_rearrengement_2023 --OT_dist_thresh 1.0 --thresh_num_dissimilar -1 --match_relations_walk --HORIZON_DT 30 --log_every 25 --dataset 2023 --eval_split combined

DATASET IS 2023
Note: mapping sliced classes to non-sliced in SOLQ
set name= test00
WARNING:py.warnings:/home/ibrahim/.local/lib/python3.8/site-packages/ai2thor/platform.py:154: UserWarning: could not connect to X Display: 0, Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key'
  warnings.warn(

Traceback (most recent call last):
  File "main.py", line 48, in <module>
    main()
  File "main.py", line 22, in main
    aithor_rearrangement = Ai2Thor_Rearrangement()
  File "/home/ibrahim/TIDEE/models/aithor_rearrange.py", line 143, in __init__
    self.two_phase_rgb_task_sampler: RearrangeTaskSampler = TwoPhaseRGBBaseExperimentConfig.make_sampler_fn(
  File "/home/ibrahim/TIDEE/rearrangement/baseline_configs/two_phase/two_phase_rgb_base.py", line 77, in make_sampler_fn
    return RearrangeTaskSampler.from_fixed_dataset(
  File "/home/ibrahim/TIDEE/rearrangement/rearrange/tasks.py", line 885, in from_fixed_dataset
    return cls(
  File "/home/ibrahim/TIDEE/rearrangement/rearrange/tasks.py", line 841, in __init__
    self.walkthrough_env = RearrangeTHOREnvironment(**rearrange_env_kwargs)
  File "/home/ibrahim/TIDEE/rearrangement/rearrange/environment.py", line 249, in __init__
    self.controller = self.create_controller()
  File "/home/ibrahim/TIDEE/rearrangement/rearrange/environment.py", line 263, in create_controller
    controller = ai2thor.controller.Controller(
  File "/home/ibrahim/.local/lib/python3.8/site-packages/ai2thor/controller.py", line 513, in __init__
    self._build = self.find_build(local_build, commit_id, branch, platform)
  File "/home/ibrahim/.local/lib/python3.8/site-packages/ai2thor/controller.py", line 1352, in find_build
    raise Exception("\n".join(error_messages))
Exception: The following builds were found, but had missing dependencies. Only one valid platform is required to run AI2-THOR.
Platform Linux64 failed validation with the following errors: Invalid display: :0. Failed to connect Can't connect to display ":0": b'Invalid MIT-MAGIC-COOKIE-1 key' 
  Linux64 requires a X11 server to be running with GLX. The following valid displays were found :1.0

**Comment by Gabesarch** [comment]
It looks like your X display is on port 1. 

You can specify to run on port 1 by adding the following argument:
`--server_port 1`

**Comment by ibrahimyousri** [comment]
It works Thanks a lot @Gabesarch  :)
